### ISSUE TITLE
Add support for Dataset Versioning Entity API

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/entity-api#101]

**Comment by libpitt** [comment]
Page on HubMAP portal that references VersionSelect: https://github.com/hubmapconsortium/portal-ui/blob/main/context/app/static/js/components/detailPage/summary/SummaryData/SummaryData.jsx

https://github.com/hubmapconsortium/portal-ui/blob/main/context/app/static/js/components/detailPage/VersionSelect/VersionSelect.jsx

**Comment by libpitt** [comment]
Where to find things on HubMAP Portal: https://github.com/hubmapconsortium/portal-ui/blob/main/context/app/static/js/components/Routes/Routes.jsx

`app.py @app.route('/datasets/<id>/revisions', methods=['GET'])`

SenNet Entity API:
Reading of `previous_revision_uuid`.
```
@app.route('/entities/<entity_type>', methods = ['POST'])
:
  # Also check existence of the previous revision dataset if specified
          if 'previous_revision_uuid' in json_data_dict:
```

**Comment by libpitt** [comment]
Results:

`GET /datasets/<id>/revisions`
- Retrieval works

`POST /entities/dataset`
- Can use a Published Dataset as `previous_revision_uuid` and create new Dataset revision thereof
- Using a Source as `previous_revision_uuid` results in 400
- Using not Published Dataset as `previous_revision_uuid` results in 400
- Using not Published Sample as  `previous_revision_uuid` results in 400 ([536465d](https://github.com/sennetconsortium/entity-api/commit/536465db3ad77fa6ef670a73f723f2e66489969f))
