### ISSUE TITLE
Add support for collections Entity API

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/entity-api#102]
See https://portal.hubmapconsortium.org/collections

HuBMAP provenance-schema: https://github.com/hubmapconsortium/entity-api/blob/main/src/schema/provenance_schema.yaml

**Comment by libpitt** [comment]
@maxsibilla 
So after looking into this, we do support POST, GET and even PUT of collections.

We currently support collections for all entity types. Yesterday you mentioned that for now we just supporting Datasets. So seems only thing to do is to add this restriction. I am thinking the config for this should reside in `app.cfg` as a list and then around line 1846 in `app.py` we can test that each `entity_dict.entity_type` conforms to this constraint.

**Comment by maxsibilla** [comment]
@libpitt what the SenNet's Entity API has is outdated in regards to collections. We need to pull over what HuBMAP has in both `app.py` as well as in the provenance. We should only support datasets belonging to a collection

**Comment by libpitt** [comment]
@maxsibilla 

It's pretty much the same (hopefully I am not missing anything). The differences I have noted with HubMAP and SenNet are the names of the methods and properties, logic same. The naming is better in SenNet. The main line of code in HuBMAP that adds the constraint is:

```
if not schema_manager.entity_type_instanceof(entity_dict[‘entity_type’], ‘Dataset’):
    bad_request_error(f”The UUID provided in JSON is not a Dataset or Publication: {dataset_uuid}“)
```

That's pretty much all that we would need to add in SenNet. 

As for the provenance schema, the property in `Collection` is called `datasets` in HuBMAP, and in SenNet `entities`. 

Just an alert code-wise: maybe it is semantically not correct in the industry to have a collection of anything but Datasets, but if in the event it could happen, then we'd need to rename the methods and properties in relation to this card/issue back to `entities`. If we'll never be hit with the case of having collections of anything but Datasets, then we're free to match exactly like what HuBMAP has currently. What do you think?
