### ISSUE TITLE
Add support for "publications" entity type

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/entity-api#113]
Additionally look into better supporting a superclass functionality. Currently the provenance schema states that the superclass of a publication is dataset (https://github.com/hubmapconsortium/entity-api/blob/eaf960ad68fc314b4187d495dc672b029277b67c/src/schema/provenance_schema.yaml#L419), however, the properties of Dataset are copied here. Ideally specifying "superclass" should be handled and no duplication of properties will be necessary.

**Comment by libpitt** [comment]
Also involved: https://github.com/hubmapconsortium/uuid-api/blob/main/src/uuid_worker.py
