### ISSUE TITLE
Investigate why Datasets can't be created via the portal

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/entity-api#123]
@bhonick  has complained about getting this error when attempting to register a Dataset in the portal. Current resolution was to simply restart the Entity API's docker container as I could not reproduce locally with the latest `dev-integrate` branch. Seems to be related to latest Publication inclusion in the provenance schema.
![image](https://github.com/sennetconsortium/entity-api/assets/7218802/c5e2dddc-cf77-4eab-bc84-f3c07b9272aa)

**Comment by libpitt** [comment]
This is as a result of https://github.com/sennetconsortium/entity-api/pull/124/files where mutations of the original dict is occurring.
