### ISSUE TITLE
Integrate `validate_constraints_new` with PUT and POST calls to ensure entities aren't created with invalid ancestry relationships

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/entity-api#140]
User are able to issue a POST or PUT call and set the `direct_ancestor_uuid` property and bypass the entity constraints used by the portal. We need to call `validate_constraints_new` during `create_entity` and `update_entity` calls.

**Comment by libpitt** [comment]
`validate_constraints_new` needs to be renamed to `validate_constraints`
