### ISSUE TITLE
Add `creation_action` specifier on Dataset registation

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/entity-api#185]
Copied from HIVE Board:

For Datasets and Publications add a new transient field used only at create/POST time to set the `creation_action` attribute of the Activity that links the Dataset/Publication to the parent entity or entities.

  - If `creation_action` is not provided at POST time, create the Activity as it is created now with the default `creation_action` field.
  - If a `creation_action` is provided, store that value in the Activity.create_action field.

Currently there is no need to return the `creation_action` on a GET as it will only be used during internal queries.

Currently, allowable values for Dataset/Publication `creation_action` are:

  - "Lab Process"
  - "HIVE Process"

**Comment by maxsibilla** [comment]
- [ ] Get a definition for the HM specific actions and discuss the actions to be set for SenNet

**Comment by tjmadonna** [comment]
Discussion on HuBMAP card
https://github.com/hubmapconsortium/entity-api/issues/533
