### ISSUE TITLE
Wireframe to handle multiple versions

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/entity-api#187]
From HIVE Board:

Create a wireframe/example layout for approval before creating the actual user interface that will exposed multiple previous and/or next versions of Datasets and Publications. Currently we only allow one previous_revision and one next_revision of a Dataset or Publication. Moving forward we will allow multiple previous or next revisions of datasets and publications.

A simple design that would replace the current next/previous links with pop-up models or dropdowns or something when there are multiple revisions seems reasonable, but let's explore with a wireframe before implementing Backend support isn't finished yet (hasn't been started) anyway.

**Comment by maxsibilla** [comment]
- [ ] Confer with HM team to see if this has been started on their end. If so then collaborate on the design and we will discuss with Bill next week. Otherwise we can discuss potential solutions

**Comment by libpitt** [comment]
@maxsibilla 

### Currently on SenNet:
![version-dropdown](https://github.com/sennetconsortium/entity-api/assets/115558393/6162a33d-13c2-4991-bd27-da2fc220720d)

Need to understand more on what the structure of this revisions data is going to look like, but given any 2 dimensional data object/array whichever, we can easily design a drop down with text input type select dropdowns.

**Root open:**
![Root-menu](https://github.com/sennetconsortium/entity-api/assets/115558393/6e3aa791-a8cc-4337-8741-0251c0b45b4c)

**Submenu:**
![Root-menu-sub-menu](https://github.com/sennetconsortium/entity-api/assets/115558393/f371ddb5-2988-496b-8a7c-9620c066a3d5)

**Comment by libpitt** [comment]
![IMG_6263](https://github.com/sennetconsortium/entity-api/assets/115558393/4f21f9d4-2119-4e0e-b83d-3bd8132ebe88)
