### ISSUE TITLE
Allow multiple revisions to be created (Gant 3.2/3.2.1)

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/entity-api#190]
From HIVE Board:

To support reorganization of existing multi-assay datatypes we need to be able to specify multiple previous and next revisions for any dataset.

Currently at create/POST time a dataset's previous version can be specified by providing the UUID of the previous dataset in the transient field `previous_revision_uuid`.

To facilitate multiple revisions: 
  

- [x] check the `link_to_previous_revision` trigger to make sure it will allow multiple datasets to be linked as previous revisions
- [x] modify the `previous_revision_uuid` field to accept either a single uuid or an array/list of uuids for linkage- will need to detect single value vs list in the `link_to_previous_revision` trigger and make modifications there to create multiple relationships if needed.
- [x] All of these changes should apply to Publications too, as they are sub-classes of Datasets.
- [x] For now we'll leave the `previous_revision_uuid` field named as is for backward compatibility, but will eventually rename to the pluralized version, `previous_revision_uuids`

The GET values of these fields will be modified in  #189 

![IMG_6263](https://github.com/sennetconsortium/entity-api/assets/115558393/6d9f1c6c-d35a-470c-9e48-6a176fcdb027)

**Comment by libpitt** [comment]
> note: The E, F, G nodes in the above graph is a special use case, because they are all revisions v4 of D and there's no ordering. We don't have to handle it in this sprint.

**Comment by libpitt** [comment]
@maxsibilla @shirey @yuanzhou @tjmadonna @DerekFurstPitt 
> For now we'll leave the previous_revision_uuid field named as is for backward compatibiltiy, but will eventually rename to the pluralized version, previous_revision_uuids

Just to note, this point appears to clash with the details of #189 where it looks like both the current singular field and pluralized field exist together.  #189 Appears to also be the more feasible option than handling both single uuid and list on the same field as expressed here: 

> modify the previous_revision_uuid field to accept either a single uuid or an array/list of uuids for linkage

Unless we are doing both, which seems like an overhead. Please clarify.

**Comment by shirey** [comment]
@maxsibilla @yuanzhou @DerekFurstPitt @tjmadonna  @libpitt Just to be clear- this is fine to do on the SenNet side of things, but on the HuBMAP side of things BOTH the existing `previous_revision_uuid` and the new  `previous_revision_uuids` need to exist at the same time until Harvard switches their UI to use the new pluralized version.
