### ISSUE TITLE
Provenance entity constraints

### ISSUE THREAD

**Issue by shirey** [sennetconsortium/entity-api#21]
The working set of constraints for provenance hierarchy (this needs to be reviewed by domain experts) are given by the following allowed direct ancestor links:
```
   Source-->organ
   organ-->block
   block-->section
   section-->suspension
   block-->block
   block-->suspension
   section-->Dataset
   suspension-->Dataset
   Dataset-->Dataset
   block-->Dataset where type of Dataset must be Lightsheet (additional datatypes may be added in future)
   organ-->suspension where type of organ must by blood
```

**Comment by maxsibilla** [comment]
@shirey Can a Dataset have another Dataset as an ancestor?

**Comment by shirey** [comment]
@maxsibilla Yes, absolutely-- I'll add Dataset --> Dataset above..

**Comment by shirey** [comment]
We will allow block-->Dataset because assays like Lightsheet work directly on a block.

**Comment by sam-dev789** [comment]
Refactored duplicate keys

   Source-->[organ]
   organ-->[block]
   block-->[section, block, suspension, Dataset]
   section-->[suspension, Dataset]
   suspension-->[Dataset]
   Dataset-->[Dataset]

**Comment by sam-dev789** [comment]
https://docs.google.com/spreadsheets/d/1nayM4XwSFyO1y_4N0osWhpIr6zSpJrWsARgXHX0si8o/edit?usp=sharing

**Comment by sam-dev789** [comment]
Constraints yaml 
https://github.com/sennetconsortium/portal-ui/commit/bc3bab320f5bf890715d8670295072fe7e1ec593#diff-b28c59b4d0b900fef904226dd34afda24e869e46349de4675173964a40adfb9eR1

**Comment by shirey** [comment]
After further conversations last week, I added the following to the constraints above-
  - On the block-->Dataset constraint the type of Dataset must be Lightsheet and additional data types to constrain against may be added in future
  - added new constraint organ-->suspension where type of organ must by blood
