### ISSUE TITLE
Modify `Collection` to support being a collection of entities rather than just a collection of datasets

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/entity-api#262]
Currently `Collections` only support a list of Datasets but we want to allow a list of any entity type

**Comment by libpitt** [comment]
Points of interest on the portal:
- https://github.com/sennetconsortium/portal-ui/blob/7b3d53583e8cb668f3fd1c13e1e7482d95146b45/src/pages/edit/collection.jsx#L74-L80
- https://github.com/sennetconsortium/portal-ui/blob/dev-integrate/src/pages/edit/collection.jsx#L356-L407
