### ISSUE TITLE
Synchronize Component Dataset status value with associated Primary Multi-Assay dataset

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/entity-api#314]
"At entity PUT, if the status of a Multi-Assay dataset is changed change the status of any Component datasets that are associated with the main Multi-Assay dataset."

Related to card https://github.com/hubmapconsortium/entity-api/issues/644

**Comment by maxsibilla** [comment]
See related HM PR https://github.com/hubmapconsortium/entity-api/pull/646

**Comment by maxsibilla** [comment]
Latest PR into main https://github.com/hubmapconsortium/entity-api/commit/061b9e4ddcc0f68c2c4068af8f21b39c9d352da4

**Comment by tjmadonna** [comment]
HuBMAP PR https://github.com/hubmapconsortium/entity-api/pull/651

Test dataset
https://data.dev.sennetconsortium.org/dataset?uuid=403fc024d236a7cd078d427a7422b480
