### ISSUE TITLE
Modify constraints wording to be clearer for data providers

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/entity-api#332]
Example error:
<img width="831" alt="image" src="https://github.com/sennetconsortium/entity-api/assets/7218802/ef5f64ac-7f64-4d7b-a003-d1f22698d2b8">
<img width="308" alt="image" src="https://github.com/sennetconsortium/entity-api/assets/7218802/29627336-804e-4555-a7b4-fd1288367f2e">

**Comment by libpitt** [comment]
![Update constraint description text](https://github.com/sennetconsortium/entity-api/assets/115558393/611921b4-1faf-4c86-a289-f256a2bb33ef)
