### ISSUE TITLE
Port over new endpoint to support optimal indexing

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/entity-api#334]
A new endpoint has been created that will be used by the Search API to speed up indexing times. See relevant commit: https://github.com/hubmapconsortium/entity-api/commit/e824932e6dd33684bcc2977102e72a0124988387

*Note: This has not been implemented by the Search API yet on HM

**Comment by tjmadonna** [comment]
This is not fully complete on the HuBMAP side yet. Waiting for them to merge into main.

**Comment by tjmadonna** [comment]
Zhou mentioned these changes might not be needed in SenNet. This is to specifically address a problem in HuBMAP.

**Comment by maxsibilla** [comment]
With the amount of entities currently in SenNet (and growing) we will need it sooner rather than later

**Comment by maxsibilla** [comment]
Related to card https://github.com/sennetconsortium/search-api/issues/192 we should add an additional modification to our Entity API to specify if a property should exist on the ancestors/descendants of an entity. In the Search API issue linked above we want `pipeline_message` to exist on the dataset but it is not necessary when the dataset is listed under `ancestors` or `descendants`. 
@libpitt
