### ISSUE TITLE
Add two new endpoints GET `/entities/<id>/collections` and GET `/entities/<id>/uploads`

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/entity-api#374]
Related to the Search API reindex optimizations

- `GET /entities/<id>/collections`: returns a list of collections that the given member entity id (either uuid or sennet_id) belongs to, support query string filtering by `?property=uuid`
- `GET /entities/<id>/uploads`: returns a list of uploads that the given entity id (either uuid or sennet_id) is associated with, support query string filtering by `?property=uuid`

**Comment by libpitt** [comment]
HM equivalent https://github.com/hubmapconsortium/entity-api/issues/674

**Comment by libpitt** [comment]
https://github.com/hubmapconsortium/entity-api/pull/686/files
