### ISSUE TITLE
Create a trigger function to detect if a processed/derived dataset has a status of `QA`

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/entity-api#429]
The provenance schema will need to be updated to support this /documents specific trigger:
```
      has_qa_derived_dataset:
        type: boolean
        on_index_trigger: get_has_qa_derived_dataset
```

The trigger itself should only fire on `Dataset`s that are primary and will check if:

- [x] The primary dataset has a processed/derived dataset (this is not for components)
- [x] The processed/derived dataset has the status of `QA`

In the scenario that a primary dataset has multiple processed/derived datasets this will return true if at least one has the status of 'QA'

**Comment by maxsibilla** [comment]
Related to https://github.com/sennetconsortium/portal-ui/issues/1575

**Comment by libpitt** [comment]
Should be working for now ...

![Image](https://github.com/user-attachments/assets/ac4a576b-01b6-4a29-b7dc-5fdda5b96aa6)
