### ISSUE TITLE
Modify elasticsearch indices to support HRA EUI

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/entity-api#461]
Link to presentation for how HM has modified their Elasticsearch to support this: https://docs.google.com/presentation/d/1TTzrqtrz6gBH-Wjy0d7gXgNHt4V2dNpM7CgonV3VhBw/edit#slide=id.p

3 queries that are made by the EUI:

1. All Samples with a rui_location
2. All Samples that have a parent from (1)
3. All Datasets that have an ancestor from (1) or (2)

3 post bodies:

```
{"version":true,"from":0,"size":10000,"stored_fields":["*"],"script_fields":{},"docvalue_fields":[],"query":{"bool":{"must":[{"term":{"entity_type.keyword":"Sample"}},{"exists":{"field":"rui_location"}}]}},"_source":{"includes":["*","uuid","entity_type","hubmap_id","sennet_id","group_uuid","group_name","last_modified_timestamp","created_by_user_displayname","donor","source","rui_location","sample_category"]}}
```
```
{"version":true,"from":0,"size":10000,"stored_fields":["*"],"script_fields":{},"docvalue_fields":[],"query":{"bool":{"must":[{"term":{"entity_type.keyword":"Sample"}},{"exists":{"field":"ancestors.rui_location"}}]}},"_source":{"includes":["*","uuid","entity_type","hubmap_id","sennet_id","group_uuid","group_name","last_modified_timestamp","created_by_user_displayname","sample_category","ancestor_ids"]}}
```
```
{"version":true,"from":0,"size":10000,"stored_fields":["*"],"script_fields":{},"docvalue_fields":[],"query":{"bool":{"must":[{"term":{"entity_type.keyword":"Dataset"}},{"exists":{"field":"ancestors.rui_location"}}]}},"_source":{"includes":["*","uuid","entity_type","hubmap_id","sennet_id","group_uuid","group_name","last_modified_timestamp","created_by_user_displayname","dataset_type","thumbnail_file","source_samples.uuid","source_samples.sample_category"]}}
```

**Comment by maxsibilla** [comment]
@bherr2 Please confirm that these are the fields you need for the HRA/EUI to exist on all entities

Ancestry fields required:

- `descendants.uuid`
- `descendants.entity_type`
- `descendants.sennet_id`
- `descendants.group_uuid`
- `descendants.group_name`
- `descendants.last_modified_timestamp`
- `descendants.created_by_user_displayname`
- `descendants.dataset_type`
- `descendants.thumbnail_file`

- `ancestors.rui_location`

**Comment by maxsibilla** [comment]
Relevant PR - https://github.com/x-atlas-consortia/hra-api/commit/183525bbb257952a5489756252206bf64cb09b06

**Comment by bherr2** [comment]
If you structure the indices like HuBMAP (and the code that queries it in that commit you reference), you will need `descendants.dataset_type` and `ancestors.rui_location` ? BASE_FIELDS + FIELDS should be in the core fields for the entities (ie they don't need to be in ancestors or descendants)

**Comment by maxsibilla** [comment]
@bherr2 We don't model it exactly like HuBMAP so with the exception of Sample Blocks, no other entity type has `ancestors` or `descendants` in elasticsearch. You can see what gets indexed here:
Suspension: https://data.sennetconsortium.org/api/json/sample?uuid=aa64cf2ffb8255db4f9d8ed653d2303e
Dataset: https://data.sennetconsortium.org/api/json/dataset?uuid=d35cd075dc392b9a11343a182d1d116b
Block: https://data.sennetconsortium.org/api/json/sample?uuid=683d27085674f6b6286e832f26e1bb08

So the following fields are on every entity: `uuid`, `sennet_id`, `entity_type`, `group_name`, `group_uuid`, `last_modified_timestamp`, `created_by_user_displayname`, `thumbnail_file` (if applicable).

If you need `descendants.dataset_type` and `ancestors.rui_location` then we can add those where applicable but if you need any other fields within descendants or ancestors let me know. We can also meet to discuss this.

**Comment by bherr2** [comment]
It might be best to meet and figure this out. I'll slack you.

**Comment by maxsibilla** [comment]
@tjmadonna 
Provenance Schema Updates:
`get_sample_block_descendants` trigger can be removed or repurposed

- `Sample` (Sections specifically):
  - `descendants`
    - `dataset_type` - Neo4j query only has to target datasets and only return this field
  - `ancestors`
    - `rui_location` - Neo4j query only has to target `Blocks` where this field exists
  -  `ancestor_ids`

- `Dataset`:
  - `ancestors`
    - `rui_location` - Neo4j query only has to target `Blocks` where this field exists
  - `source_samples` (needs to be added back
    - `uuid`
    - `sample_category`
