### ISSUE TITLE
Create new property to determine if datasets are attached to Samples

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/entity-api#506]
At Phil's request we want to be able to hide Samples that have no datasets attached to it. This could be implemented in the portal as faceted search options at each sample category level.

**Comment by tjmadonna** [comment]
Property `contains_data`

https://data.sennetconsortium.org/sample?uuid=5ed8154a19b14d3d38919bb2280d4c8c returns False

https://data.sennetconsortium.org/sample?uuid=3a72c6c5b8480fac429e3534fad742d3 returns True
