### ISSUE TITLE
Port over EPICs support

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/entity-api#523]
- [x] New creation action "external process" - https://github.com/hubmapconsortium/entity-api/blob/e58fbff12ac7d3a81778985ac89a3c3f14e0dcec/src/schema/schema_validators.py#L612
- [x] Provenance schema - https://github.com/hubmapconsortium/entity-api/blob/e58fbff12ac7d3a81778985ac89a3c3f14e0dcec/src/schema/provenance_schema.yaml#L1196
- [x] Standardized entity type `Epicollection` (e.g. https://github.com/hubmapconsortium/entity-api/blob/e58fbff12ac7d3a81778985ac89a3c3f14e0dcec/src/app.py#L1097)

**Comment by tjmadonna** [comment]
Epicollections
15d275d8767de0f54ff2768189cdcaa5
